### ISSUE TITLE
Fails due to Python3.5.2 Bug

### ISSUE THREAD

**Issue by belldandyxtq** [chainer/chainerio#28]
We need to remove Python3.5.2 from our supported version list.

For more details:
https://stackoverflow.com/questions/42942867/optionaltypefoo-raises-typeerror-in-python-3-5-2

**Comment by gwtnb** [comment]
Note: One can avoid the failure with the following code:

```python
import typing

class DummyOptional(object):

    def __getitem__(self, *args, **kwargs):
        return typing.Any

typing.Optional = DummyOptional()

import chainerio
```

I do not recommend, but it might useful.
